# ════════════════════════════════════════════════════════════════════════════
#  Nayabi Collection — Windows Setup Script (PowerShell)
#
#  Run this once after cloning:
#    Right-click this file → "Run with PowerShell"
#    OR in a PowerShell window: .\setup.ps1
#
#  If you get "cannot be loaded because running scripts is disabled":
#    Open PowerShell as Administrator and run:
#    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
# ════════════════════════════════════════════════════════════════════════════

$ErrorActionPreference = "Stop"

function Info  { Write-Host "▶ $args" -ForegroundColor Cyan }
function Ok    { Write-Host "✓ $args" -ForegroundColor Green }
function Warn  { Write-Host "! $args" -ForegroundColor Yellow }
function Err   { Write-Host "✗ $args" -ForegroundColor Red }

Write-Host ""
Write-Host "════════════════════════════════════════════════" -ForegroundColor Magenta
Write-Host "   Nayabi Collection — Local Setup (Windows)"   -ForegroundColor Magenta
Write-Host "════════════════════════════════════════════════" -ForegroundColor Magenta
Write-Host ""

# ── 1. Node.js check ─────────────────────────────────────────────────────────
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Err "Node.js is not installed."
    Write-Host "  Download it from: https://nodejs.org  (use LTS version)" -ForegroundColor Yellow
    Write-Host "  After installing, re-run this script." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}
$nodeVersion = node -v
Ok "Node.js $nodeVersion"

# ── 2. Install dependencies ───────────────────────────────────────────────────
Info "Installing dependencies (this may take a minute)…"
npm install
if ($LASTEXITCODE -ne 0) { Err "npm install failed"; Read-Host "Press Enter to exit"; exit 1 }
Ok "Dependencies installed"

# ── 3. Generate .env ─────────────────────────────────────────────────────────
# Write .env (not .env.local) — Prisma reads .env; Next.js reads both.
$envFile = ".env"
$generateEnv = $true

if (Test-Path $envFile) {
    $content = Get-Content $envFile -Raw
    if ($content -match "auto-generated by setup.ps1") {
        Warn ".env already created by setup.ps1 — leaving it untouched"
        $generateEnv = $false
    } else {
        Info "Backing up existing .env → .env.backup…"
        Copy-Item $envFile ".env.backup"
    }
}

if ($generateEnv) {
    Info "Creating .env with auto-generated secrets…"
    $secret1 = node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
    $secret2 = node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"

    @"
# auto-generated by setup.ps1 — safe to edit
DATABASE_URL="postgresql://nayabi:nayabi@localhost:5432/nayabi_collection?schema=public"
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="$secret1"
ADMIN_COOKIE_SECRET="$secret2"
NEXT_PUBLIC_APP_URL="http://localhost:3000"

# ── Optional services (store works fine without these) ────────────────────
RAZORPAY_KEY_ID=""
RAZORPAY_KEY_SECRET=""
NEXT_PUBLIC_RAZORPAY_KEY_ID=""
RESEND_API_KEY=""
RESEND_FROM_EMAIL="orders@nayabicollection.com"
RESEND_FROM_NAME="Nayabi Collection"
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
CLOUDINARY_CLOUD_NAME=""
CLOUDINARY_API_KEY=""
CLOUDINARY_API_SECRET=""
"@ | Set-Content $envFile -Encoding UTF8

    Ok ".env created (secrets auto-generated)"
}

# ── 4. Local PostgreSQL via Docker ────────────────────────────────────────────
$dockerOk = $false

if (Get-Command docker -ErrorAction SilentlyContinue) {
    # Check daemon is actually running
    $dockerInfo = docker info 2>&1
    if ($LASTEXITCODE -eq 0) {
        $existing = docker ps -a --format "{{.Names}}" | Where-Object { $_ -eq "nayabi-db" }
        if ($existing) {
            Info "Starting existing nayabi-db container…"
            docker start nayabi-db | Out-Null
        } else {
            Info "Creating local PostgreSQL container (nayabi-db)…"
            docker run -d --name nayabi-db `
                -e POSTGRES_USER=nayabi `
                -e POSTGRES_PASSWORD=nayabi `
                -e POSTGRES_DB=nayabi_collection `
                -p 5432:5432 `
                postgres:16-alpine | Out-Null
        }
        Ok "PostgreSQL container started on localhost:5432"

        Info "Waiting for the database to accept connections…"
        $ready = $false
        for ($i = 1; $i -le 30; $i++) {
            $check = docker exec nayabi-db pg_isready -U nayabi 2>&1
            if ($LASTEXITCODE -eq 0) { $ready = $true; break }
            Start-Sleep -Seconds 1
        }
        if (-not $ready) {
            Warn "Database didn't become ready in time. Try running:"
            Warn "  npm run db:push"
            Warn "  npm run db:seed"
        } else {
            Ok "Database ready"

            # ── 5. Schema + seed ────────────────────────────────────────────
            Info "Pushing database schema…"
            npm run db:push
            if ($LASTEXITCODE -ne 0) { Err "db:push failed"; Read-Host "Press Enter to exit"; exit 1 }
            Ok "Schema applied"

            Info "Seeding 16 sample products + admin user…"
            npm run db:seed
            if ($LASTEXITCODE -ne 0) { Err "db:seed failed"; Read-Host "Press Enter to exit"; exit 1 }
            Ok "Sample data loaded"
            $dockerOk = $true
        }
    } else {
        Warn "Docker is installed but Docker Desktop isn't running."
        Warn "Start Docker Desktop, wait for it to finish loading, then re-run this script."
    }
} else {
    Warn "Docker Desktop is not installed."
    Warn "Option A: Install Docker Desktop from https://www.docker.com/products/docker-desktop"
    Warn "          Then re-run this script."
    Warn ""
    Warn "Option B: Get a free database at https://neon.tech"
    Warn "          Paste its connection string into DATABASE_URL in .env"
    Warn "          Then run: npm run db:push  and  npm run db:seed"
}

# ── Done ─────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "════════════════════════════════════════════════" -ForegroundColor Green
Ok "Setup complete!"
Write-Host "════════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""
Write-Host "  Start the site:" -ForegroundColor White
Write-Host "    npm run dev" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Then open:  http://localhost:3000" -ForegroundColor Cyan
Write-Host ""
if ($dockerOk) {
    Write-Host "  Admin panel:  http://localhost:3000/admin/login" -ForegroundColor White
    Write-Host "    Email:      admin@nayabicollection.com" -ForegroundColor Gray
    Write-Host "    Password:   Admin@1234!" -ForegroundColor Gray
    Write-Host ""
    Write-Host "  DB browser:   npm run db:studio" -ForegroundColor Gray
    Write-Host ""
}
Read-Host "Press Enter to close"
