#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
#  Nayabi Collection — one-command local setup
#
#  Run this once after cloning. It will:
#    1. Verify Node.js is installed
#    2. Install dependencies
#    3. Create .env with auto-generated secrets
#    4. Start a local PostgreSQL via Docker (if the daemon is running)
#    5. Push the database schema and seed 16 sample products
#    6. Tell you how to start the site
#
#  Usage:  bash setup.sh
# ════════════════════════════════════════════════════════════════════════════

set -e

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${BLUE}▶${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}!${NC} $1"; }
err()   { echo -e "${RED}✗${NC} $1"; }

cd "$(dirname "$0")"

echo ""
echo "════════════════════════════════════════════════"
echo "   Nayabi Collection — Local Setup"
echo "════════════════════════════════════════════════"
echo ""

# ── 1. Node.js check ────────────────────────────────────────────────────────
if ! command -v node >/dev/null 2>&1; then
  err "Node.js is not installed. Install Node 20+ from https://nodejs.org and re-run."
  exit 1
fi
NODE_MAJOR=$(node -v | sed 's/v\([0-9]*\).*/\1/')
if [ "$NODE_MAJOR" -lt 20 ]; then
  warn "Node $(node -v) detected. Node 20+ is recommended."
fi
ok "Node.js $(node -v)"

# ── 2. Install dependencies ─────────────────────────────────────────────────
info "Installing dependencies (this may take a minute)…"
npm install --silent
ok "Dependencies installed"

# ── 3. Generate .env ────────────────────────────────────────────────────────
# NOTE: we write .env (not .env.local) because Prisma's CLI reads .env via
# dotenv, while Next.js reads both. Writing .env satisfies both tools.
GENERATE_ENV=0
if [ -f .env ] && grep -q "auto-generated by setup.sh" .env 2>/dev/null; then
  warn ".env already created by setup.sh — leaving it untouched"
elif [ -f .env ]; then
  info "Backing up existing .env → .env.backup and creating a fresh one…"
  cp .env .env.backup
  GENERATE_ENV=1
else
  GENERATE_ENV=1
fi

if [ "$GENERATE_ENV" = "1" ]; then
  info "Creating .env with auto-generated secrets…"
  SECRET1=$(openssl rand -hex 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  SECRET2=$(openssl rand -hex 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  cat > .env <<EOF
# auto-generated by setup.sh — safe to edit
DATABASE_URL="postgresql://nayabi:nayabi@localhost:5432/nayabi_collection?schema=public"
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="${SECRET1}"
ADMIN_COOKIE_SECRET="${SECRET2}"
NEXT_PUBLIC_APP_URL="http://localhost:3000"

# ── Optional services (the store runs fine without these) ──────────────────
# Fill in to enable payments, email, image upload, etc.
RAZORPAY_KEY_ID=""
RAZORPAY_KEY_SECRET=""
NEXT_PUBLIC_RAZORPAY_KEY_ID=""
RESEND_API_KEY=""
RESEND_FROM_EMAIL="orders@nayabicollection.com"
RESEND_FROM_NAME="Nayabi Collection"
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
CLOUDINARY_CLOUD_NAME=""
CLOUDINARY_API_KEY=""
CLOUDINARY_API_SECRET=""
EOF
  ok ".env created (NEXTAUTH_SECRET + ADMIN_COOKIE_SECRET generated for you)"
fi

# ── 4. Local PostgreSQL via Docker ──────────────────────────────────────────
# Check the daemon is actually reachable, not just that the CLI exists.
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  if docker ps -a --format '{{.Names}}' | grep -q '^nayabi-db$'; then
    info "Starting existing nayabi-db container…"
    docker start nayabi-db >/dev/null
  else
    info "Starting a local PostgreSQL (Docker container 'nayabi-db')…"
    docker run -d --name nayabi-db \
      -e POSTGRES_USER=nayabi \
      -e POSTGRES_PASSWORD=nayabi \
      -e POSTGRES_DB=nayabi_collection \
      -p 5432:5432 \
      postgres:16-alpine >/dev/null
  fi
  ok "PostgreSQL running on localhost:5432"
  info "Waiting for the database to accept connections…"
  for i in $(seq 1 30); do
    if docker exec nayabi-db pg_isready -U nayabi >/dev/null 2>&1; then break; fi
    sleep 1
  done
  ok "Database ready"

  # ── 5. Schema + seed ──────────────────────────────────────────────────────
  info "Pushing database schema…"
  npm run db:push --silent
  ok "Schema applied"

  info "Seeding 16 sample products + admin user…"
  npm run db:seed --silent
  ok "Sample data loaded"

  DB_DONE=1
else
  if command -v docker >/dev/null 2>&1; then
    warn "Docker is installed but the daemon isn't running."
    warn "Start Docker Desktop, then re-run:  bash setup.sh"
  else
    warn "Docker not found — skipping local database setup."
  fi
  warn "Alternatively, set DATABASE_URL in .env to a hosted Postgres"
  warn "(e.g. free at https://neon.tech), then run:"
  warn "    npm run db:push && npm run db:seed"
  DB_DONE=0
fi

# ── Done ────────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════"
ok "Setup complete!"
echo "════════════════════════════════════════════════"
echo ""
echo "  Start the site:    npm run dev"
echo "  Then open:         http://localhost:3000"
echo ""
if [ "${DB_DONE:-0}" = "1" ]; then
echo "  Admin panel:       http://localhost:3000/admin/login"
echo "    Email:           admin@nayabicollection.com"
echo "    Password:        Admin@1234!"
echo ""
echo "  Browse the DB:     npm run db:studio"
echo ""
fi
